# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-25 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(blank=True, max_length=50, null=True)),
                ('native_name', models.CharField(blank=True, max_length=50, null=True)),
                ('name_image', models.ImageField(blank=True, null=True, upload_to=b'')),
            ],
        ),
    ]
