# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-25 13:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('listing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.Listing')),
                ('availability', models.CharField(blank=True, max_length=21, null=True)),
            ],
            bases=('listings.listing',),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('listing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='listings.Listing')),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
            bases=('listings.listing',),
        ),
        migrations.AddField(
            model_name='listing',
            name='categories',
            field=models.ManyToManyField(to='skills.Category'),
        ),
        migrations.AddField(
            model_name='listing',
            name='skills',
            field=models.ManyToManyField(to='skills.Skill'),
        ),
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
