# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-25 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_organisation_telephone'),
        ('listings', '0002_auto_20160625_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='levels',
            field=models.ManyToManyField(to='people.Level'),
        ),
    ]
