# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-25 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('people', '0002_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skills.Category'),
        ),
    ]
