# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-25 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_level_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='telephone',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
