# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-25 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_organisation_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
